### ISSUE TITLE
Packer version is not stable with couple of plugins

### ISSUE THREAD

**Issue by AbdelrahmanDwedar** [AbdelrahmanDwedar/neovim-config#1]
In the `packer` branch I have the packer as the plugin manager I use, but it's not stable yet.

Issues: `lualine.nvim` & `nvim-tree.lua` 

These plugins doesn't get Synced and gives an error every time.

**Comment by abdulrahman1s** [comment]
Are you sure? I'm managing both of them by packer and they works really well.
Have you tried `:PackerSync`?

**Comment by AbdelrahmanDwedar** [comment]
That what causes it, it's probably something with device configs, I'll check it out later.

**Comment by AbdelrahmanDwedar** [comment]
WoW!! Finally, typos are the **worst**!!
